server:
  port: 5001
spring:
  application:
    name: userprovider
  datasource:
    url: jdbc:mysql://localhost:3306/test002?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
ProviderVersion: UserProvider001:1.0.0V